spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://bank-mysql.mysql.zhangbei.rds.aliyuncs.com:3306/gh_prd?useUnicode=true&amp;characterEncoding=UTF-8
    username: bankusr
    password: bankusr@1
  redis:
    database: 0
    password: redis@147
    sentinel:
      nodes:
        - 172.26.167.172:13101
        - 172.26.167.172:13102
        - 172.26.167.172:13103
      master: redis-master
mybatis:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
project:
  swagger:
    enable: true
    title: 单数据服务
    description: 单数据服务接口文档
  mvc:
    default-error-code: 100000
    error-expression: execution(* com.xlb.service.data..*.controller..*.*(..))
server:
  servlet:
    context-path: /data